[package]
name = "pololu-usb"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "pololu-usb-rs"
]

[dependencies]
nalgebra = "0.33.0"
nusb = "0.1.9"
plotters = "0.3.6"
pololu-usb-rs = { path = "pololu-usb-rs" }
libm = "0.2.8"
